packages:
  - frontend/apps/*
  - frontend/packages/*
  - integrations/*

catalog:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  lucide-react: 0.468.0
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 7.0.2
  vite: 7.1.9
  vitest: 3.2.4
